### PR TITLE
Add die dropped sound effect

### LINKED ISSUE #6: Satisfying sound when you drop a letter
Like a nice solid metallic or wooden "click" as a letter clicks into place.
Perhaps a happy ding after validation once you get a solution.

### PR DESCRIPTION
**Pull request by colinperepelken**
Closes #6

### CODE REVIEW

**Comment by colinperepelken** [comment]
@caitlin-hutnyk Pls review 🔉 😄

**Comment by caitlin-hutnyk** [comment]
This doesn't seem to be working on my machine :( Do I need to do any extra installation? Have you checked on all browsers? It doesn't work on chrome or safari for me

**Comment by colinperepelken** [comment]
> This doesn't seem to be working on my machine :( Do I need to do any extra installation? Have you checked on all browsers? It doesn't work on chrome or safari for me

If you are running this in the same tab, make sure you hard refresh your Chrome window with CTRL+SHIFT+R. Do you see any errors in the console?

I've only tested it on Chrome.

**Comment by xXjasonmillerXx** [comment]
I noticed some bugs with this over the weekend, the sound only played sometimes or would play delayed or multiple times :(

**Pull request merged**
